CREATE TABLE OrderHeader (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    UserId NVARCHAR(MAX) NOT NULL,
    OrderTotal FLOAT NOT NULL,
    OrderDate DATETIME2 NOT NULL,
    Status NVARCHAR(MAX) NOT NULL,
    PhoneNumber NVARCHAR(MAX) NOT NULL,
    Name NVARCHAR(MAX) NOT NULL,
    Email NVARCHAR(MAX) NOT NULL,
    PaymentIntentId NVARCHAR(MAX) NULL,
    SessionId NVARCHAR(MAX) NULL
);
GO