CREATE TABLE ResetPasswordTokens (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Token NVARCHAR(512) NOT NULL,
    ExpiresAt DATETIME2 NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UsedAt DATETIME2 NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
        ON DELETE CASCADE
);
GO

CREATE UNIQUE INDEX IX_ResetPasswordTokens_Token
    ON ResetPasswordTokens (Token);
GO